<a href="https://colab.research.google.com/github/tasnim-shamsuddin/Deep-Learning-/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
pd.read_csv("/content/aps_data.csv")

/tmp/ipython-input-1347630507.py:1: DtypeWarning: Columns (81) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("/content/aps_data.csv")

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,6,0,0,0,0,0,0,0,0,...,26,8,26,52,0,0,0,0,0,0
1,neg,90,0,0,66,0,0,0,0,0,...,1268,526,554,300,118,260,0,0,0,0
2,neg,30,na,16,14,0,0,0,0,0,...,480,84,74,50,46,0,0,0,0,0
3,neg,444,na,14,12,0,0,0,0,0,...,1614,1144,3598,2460,1258,8524,110,0,0,0
4,neg,82,na,12,10,0,0,0,0,1464,...,1010,132,310,56,92,1292,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,neg,31394,na,0,na,0,0,0,0,0,...,393008,207182,367634,267778,106778,48688,57146,638,0,0
4996,neg,1598,na,0,na,0,0,0,0,0,...,5298,3164,9710,47042,2296,1098,3288,272,0,0
4997,neg,42,2,2130706454,56,0,0,0,0,0,...,660,272,334,76,14,0,0,0,0,0
4998,neg,32752,na,0,na,0,0,0,0,0,...,533772,37122,56252,23188,1138,134,22,0,0,0
4999,neg,616,6,58,54,0,0,0,0,0,...,4630,2268,4594,2760,2108,9308,64,0,0,0

In [5]:
! git clone https://github.com/tasnim-shamsuddin/Deep-Learning-.git

Cloning into 'Deep-Learning-'...
warning: You appear to have cloned an empty repository.